"""
Django settings for refsetcollect project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import shlex

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load simple KEY=VALUE pairs from project-local .env (if present).
dotenv_path = BASE_DIR / ".env"
if dotenv_path.exists():
    for raw_line in dotenv_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ[key.strip()] = value.strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jtv*4pu$vb*j#*!(6c=lkbifouu@)d1oekfaa2hok8@0y6c4vz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

import sys
from pathlib import Path

BASE_DIR_BACKEND = BASE_DIR / "sampling_backend"
sys.path.append(str(BASE_DIR_BACKEND))

# Command prefix used to launch the sampling backend subprocess.
# Default keeps current behavior by using Django's Python interpreter.
# On the server this can point to either:
# - a dedicated Python binary, e.g. /opt/refsetcollect-tool/venv314/bin/python
# - a wrapper script, e.g. /opt/refsetcollect-tool/run_sampling.sh
# The launcher is expected to accept the sampling.py path as its first argument.
SAMPLING_LAUNCHER = shlex.split(
    os.environ.get("SAMPLING_LAUNCHER", sys.executable)
) or [sys.executable]

# Location of the NCBI taxonomy JSONL file used for fast name -> TaxID validation
TAXONOMY_JSON_PATH = os.environ.get("TAXONOMY_JSON_PATH", str(BASE_DIR / "taxonomy_all_new.jsonl"))
# Optional prebuilt SQLite lookup table (name + tax_id) for faster validation.
TAXONOMY_LOOKUP_SQLITE_PATH = os.environ.get(
    "TAXONOMY_LOOKUP_SQLITE_PATH",
    str(BASE_DIR / "taxonomy_name_taxid.sqlite3"),
)

# NCBI Datasets API
# Prefer to set via environment variable NCBI_API_KEY to avoid hard-coding secrets.
# No fallback: must be provided via environment to avoid invalid/expired keys lingering in code.
NCBI_API_KEY = os.environ.get("NCBI_API_KEY")
NCBI_DATASETS_INCLUDE = os.environ.get(
    "NCBI_DATASETS_INCLUDE",
    "genome,protein,cds,rna,seq-report"  # request sequences + reports by default
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sampling_app',   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'refsetcollect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'refsetcollect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
